gt_play: rewrite

diff --git a/gt_play b/gt_play
--- a/gt_play
+++ b/gt_play
@@ -1,78 +1,94 @@
 #!/usr/bin/env bash
 
-# SETS:
-#     player - player binary and arguments
-# RETURNS:
-#     0 - if player was detected
-#     1 - otherwise
-guess_player() {
-    # shellcheck disable=SC2153
-    if [[ -n $PLAYER ]]; then
-        player=( $PLAYER )
-    else
-        local binary chosen_binary
-        for binary in mpv mplayer2 mplayer; do
-            if hash -- "$binary" 2>/dev/null; then
-                chosen_binary=$binary
-                break
-            fi
-        done
-        if [[ -n $chosen_binary ]]; then
-            if [[ $chosen_binary == mpv ]] && mpv --no-ytdl >/dev/null 2>&1
-            then
-                player=( mpv --no-ytdl )
-            else
-                player=( "$chosen_binary" )
-            fi
-        else
-            return 1
-        fi
-    fi
+# This is needed for select_binary_ and joining arguments by space with $*.
+IFS=$' \t\n'
+
+################################################################################
+
+# Makes $_ans a reference to a variable passed as $1 and then invokes a function
+# with arguments passed as the rest.
+# TAKES:
+#     $1 — variable name to return answer to
+# [rest] — function and, optionally, arguments
+ret() {
+    declare -n _ans=$1
+    "${@:2}"
 }
 
+################################################################################
+
+# Check if $1 is a name of an existent binary.
 # TAKES:
-#     $1 - User-Agent string
-# SETS:
-#     downloader - downloader binary and its arguments (pass output file as a
-#         first argument and URL as a second)
+#     $1 — binary name
+# [rest] — (ignored)
 # RETURNS:
-#     0 - if downloader was detected
-#     1 - otherwise
-guess_downloader() {
-    if hash wget 2>/dev/null; then
-        downloader=( wget -U "$1" -O )
-    elif hash curl 2>/dev/null; then
-        downloader=( curl -L -A "$1" -o )
+#     0 — if $1 is a name of an existent binary
+#    >0 — otherwise
+has() {
+    command -v -- "$@" >/dev/null 2>/dev/null
+}
+
+# Returns a first argument (as array, split by $IFS) first field of which is
+# a name of an existent binary.
+# TAKES:
+#     $@ — commands with arguments separated by $IFS
+# RETURNS:
+#     0 — if binary was found
+#     1 — otherwise
+select_binary_() {
+    local binary
+    for binary; do
+        if has $binary; then
+            _ans=( $binary )
+            return
+        fi
+    done
+    return 1
+}
+
+# Selects a downloader. The result is an array you should append an output
+# filename and an URL to.
+# TAKES:
+#     $1 — User-Agent
+# RETURNS:
+#     0 — if downloader was found
+#     1 — otherwise.
+select_downloader_() {
+    if has wget; then
+        _ans=( wget -U "$1" -O )
+    elif has curl; then
+        _ans=( curl -L -A "$1" -o )
     else
         return 1
     fi
 }
 
+# Makes a reasonable file name from a base and an extension.
 # TAKES:
 #     $1 - a base for a filename
 #     $2 - extension
-# PRINTS:
-#     a valid file name
-make_filename() {
-    local filename=$1 extension=$2
+make_filename_() {
+    local base=$1 ext=$2
     # Remove forward slashes
-    filename=${filename//\//}
+    base=${base//\//}
     # Remove leading dots
-    filename=${filename##.}
-    # Substitue "_" if the result is empty
-    filename=${filename:-_}
+    base=${base##.}
+    # Substitute "_" if the result is empty
+    base=${base:-_}
     # Cut to 128 symbols
-    filename=${filename:0:128}
-    printf '%s.%s\n' "$filename" "$extension"
+    base=${base:0:128}
+    # Remove forward slashes
+    ext=${ext//\//}
+    # Cut to 8 symbols
+    ext=${ext:0:8}
+    # Combine
+    _ans=$base.$ext
 }
 
-################################################################################
-
+# URL-encodes a string.
 # TAKES:
-#     $1 - text
-# PRINTS:
-#     URL-encoded text
-urlencode() {
+#     $1 - string
+urlencode_() {
     local LC_ALL=C # Forces splitting strings by bytes, not by Unicode symbols
     local symbol result
     local -i i len=${#1}
@@ -83,7 +99,7 @@ urlencode() {
         fi
         result+=$symbol
     done
-    printf '%s\n' "$result"
+    _ans=$result
 }
 
 ################################################################################
@@ -92,62 +108,71 @@ urlencode() {
 #     $1 - language code
 #     $2 - text
 #     $3 - encoding
-# PRINTS:
-#     voice URL
-get_voice_url() {
-    local text=$2
+get_voice_url_() {
+    local lang=$1 text=$2 enc=$3
     if (( ${#text} > 100 )); then
         echo >&2 "W: text is too big (${#text}/100), cutting down."
         text=${text:0:100}
     fi
-    text=$(urlencode "$text")
-    # Hopefully no need in URL-encoding these two...
-    local enc=$3
-    local lang=$1
-
-    printf '%s\n' \
-        "http://translate.google.com/translate_tts?ie=$enc&tl=$lang&q=$text"
+    ret text urlencode_ "$text"
+    # shellcheck disable=SC2034
+    _ans="http://translate.google.com/translate_tts?ie=$enc&tl=$lang&q=$text"
 }
 
 # TAKES:
 #     $1 - language code
 #     $2 - text
 #     $3 - encoding
-# RETURNS:
-#     0 - if everything is OK
-#    >0 - if no downloaders were found or if a downloader failed
+print_voice_url() {
+    local url
+    ret url get_voice_url_ "$@"
+    printf '%s\n' "$url"
+}
+
+# TAKES:
+#     $1 - language code
+#     $2 - text
+#     $3 - encoding
 download() {
-    if ! guess_downloader 'Mozilla/5.0'; then
-        echo >&2 "E: can't guess downloader."
+    local -a downloader
+    if ! ret downloader select_downloader_; then
+        echo >&2 "E: can't auto-detect downloader."
         return 1
     fi
-    command -- "${downloader[@]}" \
-        "$(make_filename "$2" mp3)" \
-        "$(get_voice_url "$@")"
+    local filename url
+    ret filename make_filename_ "$2" mp3
+    ret url get_voice_url_ "$@"
+    command -- "${downloader[@]}" "$filename" "$url"
 }
 
 # TAKES:
 #     $1 - language code
 #     $2 - text
 #     $3 - encoding
-# RETURNS:
-#     0 - if everything is OK
-#    >0 - if $player is unset and can't be auto-detected or if it failed
 play() {
-    # if "-p" wasn't passed...
-    if [[ ! -v player ]]; then
-        if ! guess_player; then
-            echo >&2 "E: can't guess player."
+    local -a player
+    if [[ -v option_player ]]; then
+        player=( $option_player )
+    else
+        # shellcheck disable=SC2086,SC2153
+        if ! ret player select_binary_ ${PLAYER:+"$PLAYER"} \
+                 'mpv --no-ytdl' mplayer2 mplayer amarok audacious banshee \
+                 clementine deadbeef exaile rhythmbox xmms mpg123 bomi dragon \
+                 kaffeine parole totem vlc
+        then
+            echo >&2 "E: can't auto-detect player."
             return 1
         fi
     fi
-    command -- "${player[@]}" "$(get_voice_url "$@")"
+    local url
+    ret url get_voice_url_ "$@"
+    command -- "${player[@]}" "$url"
 }
 
 ################################################################################
 
 usage() {
-    cat >&2 <<EOF
+    echo >&2 "\
 USAGE: ${0##*/} [-gd] [-p PLAYER] [-e ENCODING] [--] LANG TEXT [TEXT...]
 
 If multiple TEXT arguments are given, they are joined by space.
@@ -155,25 +180,24 @@ If multiple TEXT arguments are given, they are joined by space.
 OPTIONS:
     -g: print voice URL, do not play
     -d: download, do not play
-    -p: specify a player (default: guess from \$PLAYER, mpv, mplayer2, mplayer)
+    -p: specify a player
     -e: specify TEXT encoding (default: UTF-8)
 
 EXAMPLES:
-    ${0##*/} en party; ${0##*/} en_US party
-EOF
+    ${0##*/} en party; ${0##*/} en_US party"
     exit 2
 }
 
-action=play
-unset player
-encoding=UTF-8
+option_action=play
+option_encoding='UTF-8'
+unset option_player
 
 while getopts 'gdp:e:' option; do
     case "$option" in
-        g) action=get_voice_url ;;
-        d) action=download ;;
-        p) player=( $OPTARG ) ;;
-        e) encoding=$OPTARG ;;
+        g) option_action=print_voice_url ;;
+        d) option_action=download ;;
+        p) option_player=$OPTARG ;;
+        e) option_encoding=$OPTARG ;;
         *) usage ;;
     esac
 done
@@ -185,14 +209,5 @@ shift "$(( OPTIND - 1 ))" || usage
 # At least one TEXT argument is required.
 (( $# < 2 )) && usage
 
-# "$*" joins arguments by the first symbol of $IFS. We save old $IFS to restore
-# it later.
-old_ifs=$IFS
-# Join TEXT arguments by space. "${*:2}" joins arguments starting with the
-# second.
-IFS=' '
-joined_text=${*:2}
-# Restore $IFS
-IFS=$old_ifs
-
-"$action" "$1" "$joined_text" "$encoding"
+# "$*" joins arguments by the first symbol of $IFS.
+"$option_action" "$1" "${*:2}" "$option_encoding"
