gt_play: split some functions

diff --git a/gt_play b/gt_play
--- a/gt_play
+++ b/gt_play
@@ -1,6 +1,91 @@
 #!/usr/bin/env bash
 
 # TAKES:
+#     $@ - binary names
+# PRINTS:
+#     first binary name found in PATH
+# RETURNS:
+#     0 - if a binary was found and printed
+#     1 - otherwise
+select_binary() {
+    local binary
+    for binary; do
+        hash -- "$binary" 2>/dev/null || continue
+        printf '%s\n' "$binary"
+        return
+    done
+    return 1
+}
+
+# SETS:
+#     player - player binary and arguments
+# RETURNS:
+#     0 - if player was detected
+#     1 - otherwise
+guess_player() {
+    # shellcheck disable=SC2153
+    if [[ -n $PLAYER ]]; then
+        player=( $PLAYER )
+    else
+        local binary
+        if binary=$(select_binary mpv mplayer2 mplayer); then
+            if [[ $binary == mpv ]] && mpv --no-ytdl >/dev/null 2>/dev/null
+            then
+                player=( mpv --no-ytdl )
+            else
+                player=( "$binary" )
+            fi
+        else
+            return 1
+        fi
+    fi
+}
+
+# SETS:
+#     downloader - function that takes:
+#         $1  - URL
+#         $2  - output file
+#        [$3] - User-Agent string
+# RETURNS:
+#     0 - if downloader was detected
+#     1 - otherwise
+guess_downloader() {
+    if hash wget 2>/dev/null; then
+        downloader() {
+            # shellcheck disable=SC2086
+            wget -O "$2" ${3+-U "$3"} "$1"
+        }
+    elif hash curl 2>/dev/null; then
+        downloader() {
+            # shellcheck disable=SC2086
+            curl -L -o "$2" ${3+-A "$3"} "$1"
+        }
+    else
+        return 1
+    fi
+}
+
+# TAKES:
+#     $1 - a base for a filename
+#     $2 - extension
+# PRINTS:
+#     a valid file name
+make_filename() {
+    local filename=$1 extension=$2
+    # Remove forward slashes
+    filename=${filename//\//}
+    # Remove leading dots
+    filename=${filename##.}
+    # Substitue "_" if the result is empty
+    filename=${filename:-_}
+    # Cut to 128 symbols
+    filename=${filename:0:128}
+    printf '%s.%s\n' "$filename" "$extension"
+}
+
+################################################################################
+
+# TAKES:
 #     $1 - text
 # PRINTS:
 #     URL-encoded text
@@ -17,6 +102,8 @@ urlencode() {
     done
     printf '%s\n' "$result"
 }
+
+################################################################################
 
 # TAKES:
 #     $1 - language code
@@ -40,20 +127,39 @@ get_voice_url() {
 }
 
 # TAKES:
-#     $@ - binary names
-# PRINTS:
-#     first binary name found in PATH
+#     $1 - language code
+#     $2 - text
+#     $3 - encoding
 # RETURNS:
-#     0 - if a binary was found and printed
-#     1 - otherwise
-select_binary() {
-    local binary
-    for binary; do
-        hash -- "$binary" 2>/dev/null || continue
-        printf '%s\n' "$binary"
-        return
-    done
-    return 1
+#     0 - if everything is OK
+#    >0 - if no downloaders were found or if a downloader failed
+download() {
+    if ! guess_downloader; then
+        echo >&2 "E: can't guess downloader."
+        return 1
+    fi
+    downloader \
+        "$(get_voice_url "$@")" \
+        "$(make_filename "$2" mp3)" \
+        'Mozilla/5.0'
+}
+
+# TAKES:
+#     $1 - language code
+#     $2 - text
+#     $3 - encoding
+# RETURNS:
+#     0 - if everything is OK
+#    >0 - if $player is unset and can't be auto-detected or if it failed
+play() {
+    # if "-p" wasn't passed...
+    if [[ ! -v player ]]; then
+        if ! guess_player; then
+            echo >&2 "E: can't guess player."
+            return 1
+        fi
+    fi
+    "${player[@]}" "$(get_voice_url "$@")"
 }
 
 ################################################################################
@@ -74,67 +180,6 @@ EXAMPLES:
     ${0##*/} en party; ${0##*/} en_US party
 EOF
     exit 2
-}
-
-# TAKES:
-#     $1 - language code
-#     $2 - text
-#     $3 - encoding
-# RETURNS:
-#     0 - if everything is OK
-#    >0 - if no downloaders were found or if a downloader failed
-download() {
-    local -a downloader
-    # Replace all slashes with underscores
-    local filename=${2//\//_}.mp3
-    local useragent='Mozilla/5.0'
-
-    if hash wget 2>/dev/null; then
-        downloader=( wget -nv -O"$filename" -U"$useragent" )
-    elif hash curl 2>/dev/null; then
-        downloader=( curl -# -o"$filename" -A"$useragent" )
-    else
-        echo >&2 'E: neither wget nor curl were found.'
-        return 1
-    fi
-
-    "${downloader[@]}" "$(get_voice_url "$@")"
-}
-
-# TAKES:
-#     $1 - language code
-#     $2 - text
-#     $3 - encoding
-# RETURNS:
-#     0 - if everything is OK
-#    >0 - if $player is empty and can't be auto-detected or if it failed
-play() {
-    # if "-p" wasn't passed...
-    if [[ ! -v player ]]; then
-        # If $PLAYER is set and not empty, grab it
-        # shellcheck disable=SC2153
-        if [[ -n $PLAYER ]]; then
-            player=( $PLAYER )
-        else
-            # Try to guess player
-            local binary
-            if binary=$(select_binary mpv mplayer2 mplayer); then
-                # If mpv was chosen by select_binary, and it supports
-                # '--no-ytdl' option, pass it.
-                if [[ $binary == mpv ]] && \
-                    mpv --no-ytdl >/dev/null 2>/dev/null;
-                then
-                    player=( mpv --no-ytdl )
-                else
-                    player=( "$binary" )
-                fi
-            else
-                echo >&2 "E: cannot auto-detect player."
-                return 1
-            fi
-        fi
-    fi
-    "${player[@]}" "$(get_voice_url "$@")"
 }
 
 action=play
